### ISSUE TITLE
Offer to help and feature request

### ISSUE THREAD

**Issue by ACPK** [mbi/django-front#16]
Thanks for an awesome tool as our Chief Marketing Officer (CMO) loves the ability to edit our site's content.

I would be interested in restricting users to what content they can edit. Is there a way to limit what user groups can edit what content?  The easiest way might be to create a second shortcut (e.g., {% front_edit "home_title" %}), and let the developer implement a permission feature themselves. For example, the developer could implement django-front on a legal page where legal has a shortcut to edit the content (e.g., the current shortcut) but everyone else can only view the content.

On another note, what features and/or bug fixes do you foresee in the near future to bring your django-front to v1.0?

**Comment by mbi** [comment]
The [current version](http://django-front.readthedocs.io/en/latest/settings.html#settings-section) only supports passing a `user` object to a function to assert whether the user can edit content or not, i.e. there is no distinction between actual content elements. 

To do that, we'd have to use a slightly more sophisticated method, where all the elements of the placeholder key (e.g. `"placeholder_name"`,  `"/some/path/"`, `"en"` for this placeholder tag `{% front_edit "placeholder_name" request.path request.LANGUAGE_CODE %}` ) are passed to this function, and it would be up to the function to decide whether to permit editing or not.

This would probably break existing implementation, so it'd have to be a separate setting.

> On another note, what features and/or bug fixes do you foresee in the near future to bring your django-front to v1.0?

Honestly, django-front hasn't changed much since it's initial release, mostly because it does one thing and I'm quite happy with what it does. I'm adding support for more editors as they become more prominent, but otherwise I'm quite content with its current state.
